version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch/config:/usr/share/elasticsearch/config
      - ./docker/elasticsearch/mappings:/usr/share/elasticsearch/mappings
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-ecomm

  kafka:
    build:
      context: .
      dockerfile: Dockerfile-kafka
    container_name: kafka
    user: "1001:1001"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./docker/kafka/kafka-data:/var/lib/kafka/data
    networks:
      - elastic-ecomm

  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile-zookeeper
    container_name: zookeeper
    user: "1001:1001"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./docker/kafka/zookeeper-data:/var/lib/zookeeper/data
      - ./docker/kafka/zookeeper-log:/var/lib/zookeeper/log
    ports:
      - "2181:2181"
    networks:
      - elastic-ecomm

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - elastic-ecomm

volumes:
  esdata:
    driver: local
  redisdata:
    driver: local

networks:
  elastic-ecomm:
    driver: bridge
