# Elasticsearch configuration for E-Commerce Search Demo
# Based on the elastic-courts repository configuration

# Basic configuration
cluster.name: "ecommerce-search-cluster"
node.name: "ecommerce-search-node"
network.host: 0.0.0.0

# Discovery settings
discovery.type: single-node

# Memory settings
bootstrap.memory_lock: true

# Security settings
xpack.security.enabled: false

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Search settings
search.max_buckets: 10000

# Vector search settings
# Enable vector search capabilities
script.allowed_types: "inline"
script.allowed_contexts: "score"

# Thread pool settings
thread_pool.search.size: 5
thread_pool.search.queue_size: 1000
thread_pool.write.size: 5
thread_pool.write.queue_size: 1000

# Index settings
action.auto_create_index: true
