# Elasticsearch configuration for e-commerce search demo

# Cluster settings
cluster.name: ecommerce-search
node.name: ecommerce-node-1

# Network settings
network.host: 0.0.0.0
http.port: 9200

# Discovery settings
discovery.type: single-node

# Memory settings
bootstrap.memory_lock: true

# Security settings
xpack.security.enabled: false

# Index settings
action.auto_create_index: true

# Search settings
search.max_buckets: 10000

# Vector search settings
# Ensure vector search is enabled (default in Elasticsearch 8.x)
